### ISSUE TITLE
[Question] Memory limitation 

### ISSUE THREAD

**Issue by jrodriguezpuigvert** [SebFar/radial_bnn#2]
First all, let me congratulate you for such an amazing job so far and thank you for releasing the code. 
The tensor shape that your implementation requires, look like this: 
[examples, samples, in_channels, H, W]
In my own experiment, I tried following configuration:

[16,1,3,192,256] and [8,2,3,192,256] 
 
I would like to increase the sample size without decreasing the batch_size. Otherwise, I am running out of memory. 

Could I keep the samples to 1 and calculate the loss, perform backpropagation and iterate over the same batch "variational_train_samples" times, without keeping all samples at the same time in memory? 

Which consequences would have such a change? 

GPU : GeForce RTX 2080 Ti

Thanks in advance, I hope I did not ask anything stupid. :smiley:

**Comment by SebFar** [comment]
Hi - Yes, this would absolutely work. The code is written to allow these steps to go in parallel, but you're just averaging over the resulting losses in either case. It won't change the math to use variational_samples=1 and do a for loop around the backprop and accumulate the losses. (Just be careful that the KL regularization is weighted correctly - it's possible you'd need to adjust that.)
